version: 0.2
phases:
  pre_build:
    commands:
      - echo "Compilando aplicación Quarkus..."
      - chmod +x ./gradlew
  build:
    commands:
      - echo "Generando JAR ejecutable..."
      - ./gradlew clean build -Dquarkus.package.type=uber-jar -x test
      - echo "JAR generado correctamente"
  post_build:
    commands:
      - echo "Preparando artifacts para Elastic Beanstalk..."
      - ls -la build/libs/
artifacts:
  files:
    - build/libs/suresell-1.0.0-SNAPSHOT-runner.jar
  name: eb-java-app-$(date +%Y-%m-%d)