name: Trigger AWS CodePipeline on Merge to Master

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CodePipeline via AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          pip install awscli --upgrade --quiet
          aws codepipeline start-pipeline-execution --name pipeline-ms-suresell-stock --region us-east-1