name: Trigger AWS Pipeline on Merge to master

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodePipeline
        uses: aws-actions/aws-cli-action@v1
        with:
          name: pipeline-ms-suresell-stock
          region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}